### ISSUE TITLE
"fetch failed" when using motorhead and "out of memory" when using Buffer Memory when using Embed or Share Chatbot UI.

### ISSUE THREAD

**Issue by AGTGreg** [FlowiseAI/Flowise#1343]
So, like the title says:

- When we use Motorhead memory 1 out of ~3-4 messages raises `fetch failed` error on the server. We write a question, we get an answer then while we wait for the the TextInput to re-enable (which takes a lot of time btw) we get a "fetch failed" message.
- When we use Buffer Memory we get `JavaScript heap out of memory` after ~15-20 messages. The TextInput still takes a lot of time to re-enable (taking logger as more messages are added). And we also upgraded our server memory to more to Flowise.

I post this as a bug because we did not have this error under the same setup when we were using an older version of Flowise. This started to appear after we upgraded to the latest version. So after the upgrade the TextInput takes a lot of time to re-enable and then we get "fetch failed" but this is after we get the response from the flow.

We run flowise in a docker container and orchestrated in docker-compose. Here is the docker-compose file:

```yaml
version: '3.7'

services:
    redis:
        image: "redis:6-alpine"
        restart: unless-stopped
        ports:
            - "6379:6379"
        command: redis-server
        volumes:
            - redis_data:/data
        logging:
            options:
                max-size: "5m"
                max-file: "3"

    motorhead:
        image: "ghcr.io/getmetal/motorhead:latest"
        restart: unless-stopped
        depends_on:
            - redis
        ports:
            - "8000:8000"
        environment:
            - PORT=8080
            - REDIS_URL=redis://redis:6379
            - MOTORHEAD_MAX_WINDOW_SIZE=40
            - MOTORHEAD_LONG_TERM_MEMORY=0
            - OPENAI_API_KEY=
            - RUST_BACKTRACE=1
        logging:
            options:
                max-size: "5m"
                max-file: "3"

    flowise:
        image: flowiseai/flowise:latest
        restart: unless-stopped
        depends_on:
            - motorhead
            - redis
        environment:
            - PORT=${PORT}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.gmc_flowise:/root/.gmc_flowise
        command: /bin/sh -c "sleep 3; flowise start"
        
volumes:
    redis_data:
```

Here is a log I created to demonstrate the issue when using Mororhead memory. The log starts with a fresh instance of Flowise and ends with the error. I do nothing except to chat though the chat UI:

```bash
flowise-flowise-1    | 2023-12-06 11:16:42 [INFO]: Starting Flowise...
flowise-flowise-1    | 2023-12-06 11:16:42 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
flowise-flowise-1    | 2023-12-06 11:16:42 [INFO]: 📦 [server]: Data Source has been initialized!
flowise-flowise-1    | 2023-12-06 11:16:56 [INFO]: ⬆️ POST /api/v1/prediction/02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b
flowise-motorhead-1  | [2023-12-06T11:16:56Z INFO  actix_web::middleware::logger] 172.19.0.6 "GET /sessions/6a538d6b-7ade-4fae-9894-c98868040c0a/memory HTTP/1.1" 200 41 "-" "node" 0.001107
flowise-flowise-1    | 2023-12-06 11:16:56 [INFO]: [server]: Chatflow 02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b added into ChatflowPool
flowise-motorhead-1  | [2023-12-06T11:16:59Z INFO  actix_web::middleware::logger] 172.19.0.6 "POST /sessions/6a538d6b-7ade-4fae-9894-c98868040c0a/memory HTTP/1.1" 200 15 "-" "node" 0.000851
flowise-flowise-1    | 2023-12-06 11:17:27 [INFO]: ⬆️ POST /api/v1/prediction/02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b
flowise-motorhead-1  | [2023-12-06T11:17:27Z INFO  actix_web::middleware::logger] 172.19.0.6 "GET /sessions/6a538d6b-7ade-4fae-9894-c98868040c0a/memory HTTP/1.1" 200 168 "-" "node" 0.000676
flowise-flowise-1    | 2023-12-06 11:17:27 [INFO]: [server]: Chatflow 02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b added into ChatflowPool
flowise-motorhead-1  | [2023-12-06T11:17:30Z INFO  actix_web::middleware::logger] 172.19.0.6 "POST /sessions/6a538d6b-7ade-4fae-9894-c98868040c0a/memory HTTP/1.1" 200 15 "-" "node" 0.000775
flowise-flowise-1    | 2023-12-06 11:17:42 [INFO]: ⬆️ POST /api/v1/prediction/02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b
flowise-motorhead-1  | [2023-12-06T11:17:42Z INFO  actix_web::middleware::logger] 172.19.0.6 "GET /sessions/6a538d6b-7ade-4fae-9894-c98868040c0a/memory HTTP/1.1" 200 346 "-" "node" 0.000665
flowise-flowise-1    | 2023-12-06 11:17:42 [INFO]: [server]: Chatflow 02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b added into ChatflowPool
flowise-motorhead-1  | [2023-12-06T11:17:46Z INFO  actix_web::middleware::logger] 172.19.0.6 "POST /sessions/6a538d6b-7ade-4fae-9894-c98868040c0a/memory HTTP/1.1" 200 15 "-" "node" 0.000883
flowise-flowise-1    | 2023-12-06 11:17:52 [INFO]: ⬆️ POST /api/v1/prediction/02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b
flowise-motorhead-1  | [2023-12-06T11:17:52Z INFO  actix_web::middleware::logger] 172.19.0.6 "GET /sessions/6a538d6b-7ade-4fae-9894-c98868040c0a/memory HTTP/1.1" 200 463 "-" "node" 0.000524
flowise-flowise-1    | 2023-12-06 11:17:52 [INFO]: [server]: Chatflow 02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b added into ChatflowPool
flowise-flowise-1    | 2023-12-06 11:17:57 [ERROR]: [server]: Error: fetch failed
flowise-flowise-1    | TypeError: fetch failed
flowise-flowise-1    |     at Object.fetch (node:internal/deps/undici/undici:11372:11)
flowise-flowise-1    |     at async RetryOperation._fn (/usr/local/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12)
```

When using Buffer memory we simple run out of memory:
```bash
flowise-flowise-1    | 2023-12-06 11:27:50 [INFO]: ⬆️ POST /api/v1/prediction/02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b
flowise-flowise-1    | 2023-12-06 11:27:50 [INFO]: [server]: Chatflow 02a3bf6d-5af0-45e5-8b7e-89f8ef70e13b added into ChatflowPool
flowise-flowise-1    |
flowise-flowise-1    | <--- Last few GCs --->
flowise-flowise-1    |
flowise-flowise-1    | [1:0x7f323f511020]   333318 ms: Mark-sweep (reduce) 980.4 (996.5) -> 980.3 (997.3) MB, 755.4 / 0.0 ms  (+ 58.8 ms in 14 steps since start of marking, biggest step 20.7 ms, walltime since start of marking 855 ms) (average mu = 0.330, current mu = 0.257) al
flowise-flowise-1    |
flowise-flowise-1    | <--- JS stacktrace --->
flowise-flowise-1    |
flowise-flowise-1    | FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
flowise-flowise-1 exited with code 139
```

The way I see it `ChatflowPool` might be the cause of this issue. We do not have any problems chatting with the flow from within Flowise where `ChatflowPool` does not fire up.
