### ISSUE TITLE
[BUG] It's not possible to have a GitHub action build an arm64 docker image

### ISSUE THREAD

**Issue by automaton82** [FlowiseAI/Flowise#1535]
**Describe the bug**
If you create a GitHub workflow action today that creates a docker image specifically for arm64, it will fail with a vague error:

```
#19 ERROR: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
------
 > [14/14] RUN yarn build:
1.967 yarn run v1.22.19
2.416 $ turbo run build
4.201 ld-linux-aarch64.so.1: /usr/src/packages/node_modules/turbo-linux-arm64/bin/go-turbo: Not a valid dynamic program
4.315 error Command failed with exit code 1.
```

**To Reproduce**
Clone this repo, then create a new GitHub workflow that contains the following in it:

```
     ... 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: flowise:latest
          platforms: linux/arm64
```

**Expected behavior**
This should build and be able to push without any errors.

**Setup**
This can be done fully on GitHub.

**Additional context**
This is due (or similar to) https://github.com/vercel/turbo/issues/5650 and was fixed in a later version of turbo.
