### ISSUE TITLE
[BUG] new release v1.8.3 breaks flowise 

### ISSUE THREAD

**Issue by mkbenon1** [FlowiseAI/Flowise#2732]
**Describe the bug**
The latest update of Flowise v1.8.3 release does not update properly. I am running my flowise on AWS and followed the instructions  on github for installation, no internal code modifications.

**To Reproduce**

1. Go to the EC2 instance in which flowise is  installed and navigate to the docker folder.
2. execute: docker-compose stop
3. docker pull flowiseai/flowise
4. execute: docker-compose up -d

Error: Flowise is not available on the IP address on the port 3000
**Expected behavior**
Flowise should be running on port3000 of the ip address

**Screenshots**
<img width="1941" alt="Screenshot 2024-06-27 at 07 45 05" src="https://github.com/FlowiseAI/Flowise/assets/152880202/c22990c5-fb40-49f9-9031-164c68241cbc">
<img width="1941" alt="Screenshot 2024-06-27 at 07 45 23" src="https://github.com/FlowiseAI/Flowise/assets/152880202/e90c8c98-8e29-4d5e-9ff4-c847a74f5443">
<img width="1941" alt="Screenshot 2024-06-27 at 07 47 34" src="https://github.com/FlowiseAI/Flowise/assets/152880202/7abd201e-77f0-4abd-94d2-0aa68e628150">
<img width="1941" alt="Screenshot 2024-06-27 at 07 48 37" src="https://github.com/FlowiseAI/Flowise/assets/152880202/511cc53d-c028-450b-b96a-14c6467250cc">
<img width="1941" alt="Screenshot 2024-06-27 at 07 50 06" src="https://github.com/FlowiseAI/Flowise/assets/152880202/250ebeb2-f052-4935-96a3-a99f4b315c0f">

**Setup**

-   Installation docker on aws
-   Flowise Version v1.8.3
-   OS:Ubuntu on aws
-   Browser chrome and safari

**Additional context**

**Comment by bigsk1** [comment]
same issue , figured it out, pull the latest repo, the Dockerfile in root has new build details, some reason the docker/Dockerfile I have along with the docker-compose.yml isn't updated, maybe I added that before myself but, anyway I built the image from root Dockerfile, then cd to docker/ folder and fixed the new .yml  , this changed

remove   

```bash
  command: /bin/sh -c "sleep 3; flowise start"
```

add   

```bash
entrypoint: /bin/sh -c "sleep 3; pnpm start"  
```

 ```yaml
 services:
    flowise:
        image: flowise:latest
        restart: unless-stopped
        environment:
            - PORT=${PORT}
            - CORS_ORIGINS=${CORS_ORIGINS}
            - IFRAME_ORIGINS=${IFRAME_ORIGINS}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
            - DEBUG=${DEBUG}
            - DATABASE_PATH=${DATABASE_PATH}
            - DATABASE_TYPE=${DATABASE_TYPE}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_SSL=${DATABASE_SSL}
            - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
            - APIKEY_PATH=${APIKEY_PATH}
            - SECRETKEY_PATH=${SECRETKEY_PATH}
            - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
            - LOG_LEVEL=${LOG_LEVEL}
            - LOG_PATH=${LOG_PATH}
            - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
            - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
            - MODEL_LIST_CONFIG_JSON=${MODEL_LIST_CONFIG_JSON}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        entrypoint: /bin/sh -c "sleep 3; pnpm start" 
```
