### ISSUE TITLE
How can I use Chroma 

### ISSUE THREAD

**Issue by choihoo1018** [FlowiseAI/Flowise#342]
Hello,
When I using Chroma,a problem occurred
![hiworks_20230616_9081](https://github.com/FlowiseAI/Flowise/assets/25859270/553a1a48-5dce-420f-a36b-2f84296563a4)

What the problem?

**Comment by kmashal** [comment]
I have the same issue ?

**Comment by HenryHengZJ** [comment]
currently running both flowise and chroma on docker won't work.

here's the guide - https://docs.flowiseai.com/vector-stores/chroma

**Comment by av8dtop** [comment]
u can deploy chroma docker
use chroma url

**Comment by adryanm2m** [comment]
_currently running both flowise and chroma on docker won't work._

I got the same issue with or without the chroma url

Has this been resolved?

**Comment by chungyau97** [comment]
Hi @adryanm2m,

1. Clone [Chroma Repo](https://github.com/chroma-core/chroma)
2. Add below code into Chroma's [docker-compose.yml](https://github.com/chroma-core/chroma/blob/main/docker-compose.yml)
```
  flowise:
    platform: linux/x86_64
    image: flowiseai/flowise
    restart: always
    env_file:
      - ./flowise.env
    ports:
      - "${FLOWISE_PORT:-3000}:3000"
    volumes:
        - ~/.flowise:/root/.flowise
    command: /bin/sh -c "sleep 3; flowise start"
```
3. Run `docker compose up -d --build`
4. Specify this Chroma URL http://host.docker.internal:8000 assuming you use port 8000
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/f8296b34-2946-4aa5-b454-61adee855754)

Do come join our (Discord)[https://discord.gg/AfZaQA5k]. 
You can find this solution in Support Channel > `Trying to use Chain Tool with Chat Prompt Template failing`
