### ISSUE TITLE
[BUG] ChatOllama with function is missing

### ISSUE THREAD

**Issue by erlebach** [FlowiseAI/Flowise#3613]
@HenryHengZJ 

**Describe the bug**
I installed flowise with Docker using docker-compose.yml: 
```
Press ENTER or type command to continue
version: '3.1'

services:
  flowise:
    image: flowiseai/flowise:latest
    restart: always
    environment:
      - PORT=${PORT}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ~/.flowise:/root/.flowise
    entrypoint: /bin/sh -c "sleep 3; flowise start"
```

**To Reproduce**
1) Execute `docker compose up -d`
2) Point a browser (Safari) to `localhost:3000`
3) Search for Ollama in both agents and chat nodes, and observe that Chat Ollama with Functions is not present. 

How do I fix this issue? Without using Docker, I can use Flowise, but the Marketplace is a blank page. On the other hand, Ollama Chat with functions is present. 

**Expected behavior**
I expect the same nodes to be available whether I use Docker or not to install Flowise. Perhaps the Docker file should be updated. 

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: macOS with Sequoia on M2. 
-   Browser: Safari

I checked that without using Docker, ChatOllama with Functions is also not present.
