### ISSUE TITLE
[BUG] flowise embedding is not properly showing on the UI even if the pricing seems to show up ok

### ISSUE THREAD

**Issue by rossm-mf** [FlowiseAI/Flowise#4141]
**Describe the bug**
When looking at the logs, I can see pricing for embedding documents but nothing on the size token used

**To Reproduce**

See the logs section

**Expected behavior**
I see the price but not how many token used

**Screenshots**

![Image](https://github.com/user-attachments/assets/e2936b99-16a7-4ba9-89f6-e4218fb4880a)

**Comment by Hetsavani** [comment]
can you please provide detailed steps on how to reproduce?

**Comment by rossm-mf** [comment]
hard to know how to reproduce if it's use latest docker image and hook embedding models in litellm. it seems to do it with both openai and azure embedding-large. It doesnt seems to change if it comes from Openwebui or Flowise.

![Image](https://github.com/user-attachments/assets/0af179f3-4d20-4eda-b7b6-a443fb581067)

My config

```
  - model_name: azure/text-embedding-3-large
    model_info:
      mode: embedding
    litellm_params: 
      model: azure/text-embedding-3-large
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: "2023-05-15"

  - model_name: openai/text-embedding-3-large
    litellm_params: 
      model: openai/text-embedding-3-large
      api_key: os.environ/OPENAI_API_KEYS
    model_info:
      mode: embedding
```

the general configs

```
general_settings:
  background_health_checks: False
  store_model_in_db: True
  # Only USE when running LiteLLM on your VPC. Allow requests to still be processed even if the DB is unavailable. We recommend doing this if you're running LiteLLM on VPC that cannot be accessed from the public internet.
  allow_requests_on_db_unavailable: True 

litellm_settings:
  # Switch off Debug Logging, ensure your logs do not have any debugging on
  set_verbose: True
  json_logs: True
  turn_off_message_logging: True
```
