### ISSUE TITLE
[BUG] Docker flowise stop responding

### ISSUE THREAD

**Issue by kungl** [FlowiseAI/Flowise#4452]
**Describe the bug**
I'm using the docker version of flowise (2.2.7-patch.1 and/or 2.2.5) with the default configuration in AWS, and after a few days, the docker container doesn't answer, and I need to restart docker. No error logs. After the restart works as expected. I'm using beanstalk and default env vars.

**To Reproduce**
Just run a new application in docker on AWS Beanstalk / Amazon Linux 2003.

docker-compose.yml
```
services:
  nginx:
    image: nginx:1.27.4
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/log/nginx/healthd:/var/log/nginx/healthd

  flowise:
    image: <OWN_REPO>/flowise:prod-2.2.5
    container_name: flowise
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    entrypoint: /bin/sh -c "sleep 3; flowise start"
```

.env
```
PORT=80
APIKEY_PATH=/root/.flowise
DATABASE_PATH=/root/.flowise
SECRETKEY_PATH=/root/.flowise
LOG_PATH=/root/.flowise/logs
BLOB_STORAGE_PATH=/root/.flowise/storage
APIKEY_STORAGE_TYPE=db
CORS_ORIGINS=*
IFRAME_ORIGINS=*
STORAGE_TYPE=local
DATABASE_TYPE=postgres
DATABASE_PORT=5432
DATABASE_HOST=RDS
DATABASE_NAME=flowise
DATABASE_USER=flowise
DATABASE_PASSWORD=<REDACTED>
DATABASE_SSL=false
SECRETKEY_STORAGE_TYPE=aws
SECRETKEY_PATH=/root/.flowise
FLOWISE_SECRETKEY_OVERWRITE=<REDACTED>
SECRETKEY_AWS_REGION=eu-west-1
FLOWISE_USERNAME=<REDACTED>
FLOWISE_PASSWORD=<REDACTED>
```

**Setup**

-   Installation: Docker version 25.0.8, build 0bab007
-   Flowise Version: 2.2.5
-   Database Version: Postgresql 17.4
-   OS: Amazon Linux 2023

**Additional context**

Respone after 2-3 days
```
curl localhost/api/v1/ping
curl: (52) Empty reply from server
```

logs/server-error.log is empty. Based on the metrics, there is no load on the server.
