### ISSUE TITLE
[BUG] Workers are not starting after upgrading to 3.0.1

### ISSUE THREAD

**Issue by SamuelHassine** [FlowiseAI/Flowise#4544]
**Describe the bug**

Workers are not starting after upgrading to 3.0.1:

```
2025-05-30 09:14:28 [ERROR]: unhandledRejection: (0 , utils_1.getMulterStorage) is not a function
TypeError: (0 , utils_1.getMulterStorage) is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/flowise/dist/routes/attachments/index.js:11:66)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/flowise/dist/routes/index.js:9:39)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/flowise/dist/index.js:49:34)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
```

**Comment by SamuelHassine** [comment]
Hello @HenryHengZJ,

I'm using local storage or database storage when possible (no s3). I've rolled back to 3.0.0 and everything is working well. I don't know exactly how to reproduce. 

On Discord, it seems I'm not the only one.

**Comment by HenryHengZJ** [comment]
is it on Docker? or local pnpm installation?

**Comment by SamuelHassine** [comment]
Hello,

It is a Docker installation.

Kind regards,
Samuel

**Comment by czepan** [comment]
We have the same problem in our docker swarm setup, here is an example stack file:

```
services:
  redis:
    image: redis/redis-stack-server:latest
    hostname: ${STACK}_redis # Der Hostname wird im Swarm-Modus nicht direkt verwendet, aber kann für interne DNS-Auflösung nützlich sein.
    volumes:
      - ./volumes/redis/data:/data
    networks:
      - mandator_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    hostname: ${STACK}_postgres
    environment:
      POSTGRES_DB: flowisedb
      POSTGRES_USER: flowise
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - mandator_network
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowise -d flowisedb"]
      interval: 5s
      timeout: 5s
      retries: 5

  flowise-main:
    image: flowiseai/flowise
    hostname: ${STACK}_flowise-main
    environment:
      # Flowise Konfiguration
      PORT: 3000
      MODE: queue
      WORKER_CONCURRENCY: 10000
      QUEUE_NAME: flowise-queue
      QUEUE_REDIS_EVENT_STREAM_MAX_LEN: 10000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: flowisedb
      DATABASE_USER: flowise
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SECRET_KEY: ${FLOWISE_SECRET_KEY}
      ENABLE_METRICS: 'true'
      METRICS_PROVIDER: prometheus
      METRICS_INCLUDE_NODE_METRICS: 'true'
      FLOWISE_USERNAME: user
      FLOWISE_PASSWORD: ${FLOWISE_PASSWORD}
    volumes:
      - ./volumes/flowise/data:/root/.flowise
    networks:
      - core_wan
      - mandator_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        # Traefik Konfiguration für HTTP
        - traefik.enable=true
        - traefik.docker.network=core_wan
        - traefik.http.routers.${STACK}.rule=Host(`${FLOWISE_FQDN}`)
        - traefik.http.routers.${STACK}.entrypoints=core_wan_80
        - traefik.http.services.${STACK}.loadbalancer.server.port=3000

        # Traefik Konfiguration für HTTPS (DMZ)
        - traefik.http.routers.${STACK}-ssl.rule=Host(`${FLOWISE_FQDN_DMZ}`)
        - traefik.http.routers.${STACK}-ssl.entrypoints=core_wan_80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  flowise-worker:
    image: flowiseai/flowise
    hostname: ${STACK}_flowise-worker
    entrypoint: /bin/sh -c "sleep 3; flowise worker"
    environment:
      MODE: queue
      WORKER_CONCURRENCY: 10000
      QUEUE_NAME: flowise-queue
      QUEUE_REDIS_EVENT_STREAM_MAX_LEN: 10000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./volumes/flowise/data:/root/.flowise
    networks:
      - mandator_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  core_wan:
    external: true
  mandator_network:
    driver: overlay
    attachable: true
```

So basically nothing fancy. We in fact tried to completely reset our stack by deleting everything in the volumes and still the workers don't come up.

![Image](https://github.com/user-attachments/assets/3b4e05d4-7242-4ec4-aca7-46c837f96097)

seems like a general problem to us

![Image](https://github.com/user-attachments/assets/655bcb14-d598-4db5-9169-63ec59aa39ff)
